'use client'

import React, { useState } from 'react'
import CodeBlock from './CodeBlock'
import { IconCode, IconCopy, IconCheck } from './Icons'
import { copyToClipboard } from '@/lib/clipboard'

interface BoilerplateDisplayProps {
  boilerplate: string
}

interface ParsedFile {
  filename: string
  content: string
  language: string
}

function getLanguage(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() || ''
  const langMap: Record<string, string> = {
    ts: 'typescript', tsx: 'tsx', js: 'javascript', jsx: 'jsx',
    json: 'json', css: 'css', scss: 'scss', html: 'html',
    md: 'markdown', yml: 'yaml', yaml: 'yaml', env: 'env',
    prisma: 'prisma', sql: 'sql', sh: 'bash', py: 'python',
  }
  return langMap[ext] || 'text'
}

export default function BoilerplateDisplay({ boilerplate }: BoilerplateDisplayProps) {
  const [expandedFiles, setExpandedFiles] = useState<Record<number, boolean>>({ 0: true })
  const [copied, setCopied] = useState(false)
  const [copiedFile, setCopiedFile] = useState<number | null>(null)
  const [showAll, setShowAll] = useState(false)

  // Extract file structure
  let fileStructure = ''
  const structureMatch = boilerplate.match(/==== FILE STRUCTURE ====\n([\s\S]*?)(?=\n==== FILE:|$)/)
  if (structureMatch) {
    fileStructure = structureMatch[1].trim()
  }

  // Parse boilerplate into files
  const files: ParsedFile[] = boilerplate.split('==== FILE:').slice(1).map(section => {
    const lines = section.trim().split('\n')
    const filename = lines[0].replace(/====/g, '').trim()
    const content = lines.slice(1).join('\n').trim()
    return { filename, content, language: getLanguage(filename) }
  })

  const visibleFiles = showAll ? files : files.slice(0, 5)

  const toggleFile = (index: number) => {
    setExpandedFiles(prev => ({ ...prev, [index]: !prev[index] }))
  }

  const handleCopyAll = async () => {
    await copyToClipboard(boilerplate)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleCopyFile = async (content: string, index: number) => {
    await copyToClipboard(content)
    setCopiedFile(index)
    setTimeout(() => setCopiedFile(null), 2000)
  }

  return (
    <div className="glass-card rounded-xl p-6 md:p-8">
      <div className="flex items-center justify-between mb-8 border-b border-slate-700/50 pb-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-cyan-500/10 border border-cyan-500/15 flex items-center justify-center">
            <IconCode className="w-5 h-5 text-cyan-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold text-white">Project Boilerplate</h2>
            <p className="text-xs text-slate-500">Generated by Agent 2 — Scaffolder &bull; {files.length} files</p>
          </div>
        </div>
        <button
          onClick={handleCopyAll}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800/80 hover:bg-slate-700 text-slate-300 rounded-lg text-sm transition-all border border-slate-700/50 hover:border-slate-600"
        >
          {copied ? (<><IconCheck className="w-3.5 h-3.5 text-emerald-400" /> Copied</>) : (<><IconCopy className="w-3.5 h-3.5" /> Copy All</>)}
        </button>
      </div>
      
      {/* File Structure */}
      {fileStructure && (
        <div className="mb-6 bg-[#0d1117] rounded-xl border border-slate-800 overflow-hidden">
          <div className="px-4 py-2.5 bg-slate-800/50 border-b border-slate-700/50 flex items-center gap-2">
            <svg className="w-4 h-4 text-cyan-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z" /></svg>
            <span className="text-sm font-medium text-slate-300">Folder Structure</span>
          </div>
          <pre className="p-4 text-cyan-300 text-sm overflow-x-auto custom-scrollbar">
            <code>{fileStructure}</code>
          </pre>
        </div>
      )}

      {/* Individual Files */}
      <div className="space-y-3">
        {visibleFiles.map((file, i) => (
          <div key={i} className="bg-[#0d1117] rounded-xl border border-slate-800 overflow-hidden transition-all">
            <div
              onClick={() => toggleFile(i)}
              className="w-full text-left px-4 py-3 hover:bg-slate-800/30 flex items-center justify-between transition-colors cursor-pointer"
            >
              <div className="flex items-center gap-3">
                <span className="text-slate-500 text-xs font-mono">
                  {expandedFiles[i] ? '▼' : '▶'}
                </span>
                <span className="text-xs text-slate-600 bg-slate-800 px-2 py-0.5 rounded font-mono">
                  {file.language}
                </span>
                <code className="text-cyan-300 text-sm font-medium">{file.filename}</code>
              </div>
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  handleCopyFile(file.content, i)
                }}
                className="text-xs text-slate-500 hover:text-white transition-colors px-2 py-1 rounded hover:bg-slate-800"
              >
                {copiedFile === i ? <IconCheck className="w-3.5 h-3.5 text-emerald-400" /> : <IconCopy className="w-3.5 h-3.5" />}
              </button>
            </div>
            
            {expandedFiles[i] && (
              <div className="border-t border-slate-800 animate-slide-down">
                <div className="p-4 md:p-6 text-slate-300 font-mono text-sm overflow-x-auto custom-scrollbar">
                  <CodeBlock code={file.content} language={file.language} />
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {files.length > 5 && (
        <button
          onClick={() => setShowAll(!showAll)}
          className="mt-6 w-full py-3 bg-slate-900/50 hover:bg-slate-800/50 border border-slate-700/30 text-slate-400 hover:text-white rounded-xl text-sm transition-all flex items-center justify-center gap-2"
        >
          {showAll ? '▲ Show Less' : `▼ Show All ${files.length} Files`}
        </button>
      )}
    </div>
  )
}
